resp_treinamento = [
	#Questão 2(Que argumento você utilizaria para convencer um(a) amigo(a) a estudar, ou não, no IFBA?)
	('Ensino médio técnico, gratuito e de qualidade','Positivo'),
	('Qualidade de ensino, profissionais qualificados, estrutura do campus, etc..','Positivo'),
	('É de graça e tem um ótimo ensino ','Positivo'),
	('É um instituto de ensino de qualidade, com professores qualificados, já sai com uma formação pronto para o mercado de trabalho.', 'Positivo'),
	('a qualidade de ensino e o curso técnico ', 'Positivo'),
	('Pela qualidade do ensino e pela estrutura. Talvez não indicaria pela distância da moradia da pessoa', 'Neutro'),
	('iria tentar convencer mostrando os resultados finais do ensino, que é um ensino de qualidade e gratuito, recebendo também um curso técnico de sua escolha', 'Positivo'),
	('Ensino de qualidade, ótimas estruturas para pesquisa, e nos possibilita sair daqui com uma especialização técnica.', 'Positivo'),
	('falaria sobre o nível de ensino do instituto comparado a outros colégios e a experiência que estou tendo aqui', 'Positivo'),
	('O IFBA é uma escola técnica que tem uma ótima qualidade de ensino, professores super capacitados, e bem estruturada. ', 'Positivo'),
	('Boa estrutura, qualidade de ensino, qualificação dos profissionais para tal cargo. ', 'Positivo'),
	('é uma instituição de qualidade que te prepara para vestibular, e mesmo que você não queira fazer um curso superior teria oportunidades de emprego com o ensino técnico', 'Positivo'),
	('A qualidade de ensino, a estrutura, os cursos técnicos e o apoio ao aluno.', 'Positivo'),
	('ensino médio de qualidade e pelos cursos profisionalizantes', 'Positivo'),
	('A qualidade do ensino é muito boa e se você tiver interesse em cursar alguma faculdade, o ifba é um ótimo preparo para vestibulares. Caso você não tenha interesse em fazer um ensino superior você já sai preparado para arrumar um bom emprego.', 'Positivo'),
	('a qualidade do ensino é melhor do de qualquer outro instituto educacional do pais', 'Positivo'),
	('por causa do ensino que é ótimo aqui', 'Positivo'),
	('bons professores, boa estrutura...', 'Positivo'),
	('A qualidade do ensino, tudo que a instituição pode oferecer, e os cursos técnicos, entre outros. ', 'Positivo'),
	('que o IFBA é uma chance única onde você vai ter muitas experiências, boas e ruins. Mas é bom saber que esse instituto não é lugar para alunos que não se esforçam nem nada do tipo, pois tais sempre acabam na pior no final. aconselho a estudar bastante para fazer a prova e mais ainda se conseguir passar.', 'Positivo'),
	('melhor ensino, á recursos melhores, professores capacitados na sua matéria, além de você já sair especializado em uma área.', 'Positivo'),
	('ensino e estrutura muito bom....', 'Positivo'),
	('Que no IFBA há mais oportunidades, como cursos de línguas, além da estrutura da escola que é muito boa.', 'Positivo'),
	('os estudantes do ifba sai com um curriculum muito bom o estuda daqui e excelente e os professores qualificados', 'Positivo'),
	('Que a escola pode proporcionar um ensino de qualidade', 'Positivo'),
	('infraestrutura boa, ensino de qualidade diferente de outras escolas', 'Positivo'),
	('BOA PREPARAÇÃO PARA VESTIBULARES ', 'Positivo'),
	('Eu diria que é uma boa escolha estudar nesta instituição de ensino, pois há além de uma boa estrutura um ensino de qualidade com profissionais qualificados, e uma boa metodologia de ensino. ', 'Positivo'),
	('pelo ensino e pelas oportunidades que o IFBA da', 'Positivo'),
	('Usaria argumentos tanto da qualidade de ensino que a instituição promove em relação as demais redes de ensino local,  quanto a incrível infraestrutura que o campus possibilita.', 'Positivo'),
	('Eu argumentaria dizendo que o ensino do IFBA tem uma excelente qualidade,', 'Positivo'),
	('investimento em pesquisa e extenção, coisa rara na educação, assim acarretando a melhor ensino dando oportunidade de estudar e pratica o que estudou, dando mais chance para que os alunos aprenda alem da sala.', 'Positivo'),
	('convenceria falando que tem  muitas oportunidades  vários  curso professores de boa qualidade .ñ pois se voce for uma pessoal que tem muitos problemas o ifba ñ sera o melhor lugar para estudar', 'Neutro'),
	('convenceria falando que tem  muitas oportunidades  vários  curso professores de boa qualidade .ñ pois se voce for uma pessoal que tem muitos problemas o ifba ñ sera o melhor lugar para estudar ', 'Neutro'),
	('Que os cursos são profissionalizantes e pode ajudar bastante no futuro para ingressar em trabalhos com salários suficiente para fazer o que gosta. A não estudar porque mexe muito com o psicológico.', 'Neutro'),
	('Bons conteúdos, bom ensino e uma ótima base para o futuro mercado de trabalho.', 'Positivo'),
	('falaria que é um bom curso e ajuda no futuro', 'Positivo'),
	('Vai lhe dar um ótimo futuro, experiência e entendimento.', 'Positivo'),
	('É um Instituto Federal, que além de agregar conhecimentos à base comum curricular, também desenvolve o aluno para o meio técnico-formacional.', 'Positivo'),
	('recomendaria pelo fato de ser um bom ensino, mas não recomendaria, pois está havendo superlotação de atividades e provas para uma unica semana, e isso pode ocasionar problemas psicológicos.', 'Negativo'),
	('Venha pro IFBA pois o ensino daqui é melhor que o das outras escolas estaduais da região.', 'Positivo'),
	('de que o ifba oferta um ensino médio de qualidade', 'Positivo'),
	('seria uma oportunidade unica pois o ifba exige mais do muitas escolas o que te prepara melhor', 'Positivo'),
	('Ensino muito bom, você pode se estressar as vezes mais é perfeitamente normal.', 'Neutro'),
	('"O ensino é algo surpreendente. Apesar de ser algo complicado, não é impossível, e não ajuda você apenas no aumento do conhecimento, mas também como pessoa."', 'Positivo'),
	('Ensino médio técnico, gratuito e de qualidade', 'Positivo'),
	('Que é um ensino público de qualidade', 'Positivo'),
	('O IFBA é a melhor instituição de ensino público, com cursos técnicos. Você já sai preparado para a vida profissional.', 'Positivo'),
	('ensino de qualidade e pela competência de ensino ', 'Positivo'),
	('para ter um ensino melhor e mais chances no futuro ', 'Positivo'),
	('Ensino técnico de qualidade e grandes possibilidades para o futuro.', 'Positivo'),
	('ensino de qualidade, inclusão, consta no currículo', 'Positivo'),
	('Bons professores,  entretanto as datas das provas e trabalhos ficam muito perto das outras', 'Neutro'),
	('que é o melhor ensinooo medio da regiao', 'Positivo'),
	('um dos melhores (se não o melhor) ensino da região.', 'Positivo'),
	('Para convencê-lo, utilizaria de que o argumento de que o ensino oferecido é avançado e de boa qualidade e que o curso profissionalizante pode representar novas possibilidades para o futuro. Já na parte dos contras, eu citaria um dos aspectos mais negativos do IFBA: a superlotação de conteúdo e atividades, no momento em que escrevo isso me encontro bastante alarmada com o número de provas e trabalhos pra serem entregues em um prazo curtíssimo sendo que, na última noite, dormi pouco mais de três horas apenas devido as múltiplas obrigações escolares com que tive que lidar nessa semana, neste aspecto o IFBA não proporciona nenhum senso de flexibilidade e devo dizer que a experiência não vem sendo nada saudável, nem emocionalmente, nem intelectualmente.', 'Positivo'),
	('A qualidade do ensino é excelente, sem contar nas oportunidades de conhecer novas culturas, sem contar que por ser uma instituição federal, seria mais fácil achar um trabalho, por conta do histórico escolar. ', 'Positivo'),
	('Que o ensino é muito bom, e que traz um currículo bom para o futuro', 'Positivo'),
	('É importante o estudo da área no mundo de tecnologias que ivvemos hoje', 'Positivo'),
	('tu pode mudar o mundo; ultrapassar fronteiras tanto na Terra quanto no espaço', 'Positivo'),
	('O fato do ensino ser muito bom, além de ser uma oportunidade para o individuo se profissionalizar', 'Positivo'),
	('Lá tem professores renomados, e assistência estudantil ', 'Positivo'),
	('Experimente, pois é uma área boa, além de que o ensino lá é de qualidade.', 'Positivo'),
	('Os beneficios de entrar.......................', 'Neutro'),
	('É um ensino de ótima qualidade, que possui pesquisa e extensão, abre muitas oportunidades e te prepara para o mercado de trabalho, além dos ótimos professores que são qualificados e uma estrutura muito boa', 'Positivo'),
	('Não tentaria convencer nenhum amigo.', 'Negativo'),
	('Ótimos professores, uma boa estrutura.', 'Positivo'),
	('Apresenta boa qualidade de ensino e proporcionaria ao estudante uma boa experiência', 'Positivo'),
	('um local onde existe ser humano de verdade ,onde pessoas irão lhe acolher onde o ensino é de muita qualidade , e tem uma estrutura de encher os olhos.', 'Positivo'),
	('O ARGUMENTO QUE EU UTILIZARIA SERIA POR INSTITUTO TER UM ENSINO DE QUALIDADE E QUE COM BASE NOS ASSUNTO QUE ESTUDAM NO INSTITUTO OS ESTUDANTES TERÁ MAIS CHANCES DE INGRESSAR EM UMA UNIVERSIDADE PÚBLICA.', 'Positivo'),
	('Diria que aqui no IFBA, encontram -se cursos técnicos que não são ofertados por outras instituições.', 'Positivo'),
	('convencaria sim diria que o ifba  é uma escola de um ensino muito boa', 'Positivo'),
	('Sempre que falo do IFBA para alguém já começo falando da sua estrutura tanto aparentemente quanto tecnicamente, pois o IFBA é um Instituto de grande porte e independente dos abalos governamentais, ta ai resistindo firme e forte ao meu ver. e o IFBA é uma porta de fácil acesso para quem quer ter um futuro promissor claro, que quando digo FÁCIL quero dizer para quem estuda e tem objetivos.', 'Positivo'),
	('A estudar porque o IFBA tem ensino de qualidade ', 'Positivo'),
	('um instituto federal possui uma infraestrutura mioto boa, um ensino de qualidade, possui o diploma bem mais socorrido no ifba.', 'Positivo'),
	('ensino de qualidade', 'Positivo'),
	('Tentaria convencê-lo a estudar pelo ensino e aprendizado que é muito bom. ', 'Positivo'),
	('Ensino de qualidade, com professores altamente qualificados', 'Positivo'),
	('vale a pena, pois o ensino é aprofundado e eficiente.', 'Positivo'),
	('Este curso irá proporcionar ao  profissional aplicar conhecimentos sobre a tecnologia da informação e solucionar problemas das diversas sub-áreas das ciências agrarias .', 'Positivo'),
	('Falaria: se você pretende trabalhar em algo na área que os cursos abrangem, lá é um bom lugar para se formar.', 'Positivo'),
	('a instituição conta com profissionais capacitados tanto professores quanto a profissionais da área de saúde ocasionando um maior desenvolvimento intelectual e ensino de qualidade aos seus alunos', 'Positivo'),
	('A qualidade de ensino e o incentivo à pesquisas. Além da quantidade de eventos culturais e o auxílio para quem precisa. ', 'Positivo'),
	('No IFBA você ira aprender e se elevar muito nos estudos. Terá uma grande vantagem nos concursos e vestibulares e também poderá até achar um emprego mais fácil. ', 'Positivo'),
	('Ele(a) poderia obter um ensino superior de qualidade e gratuito. Além do campus estar próximo à diversos cidades e comunidades da Chapada Diamantina. Também teria chance de obter um auxilio financeiro para continuar no campus e se manter. Além de alguns ótimos professores que são quase como pais para muitos alunos, aconselhando e orientando tanto pessoalmente quando profissionalmente.', 'Positivo'),
	('A estudar,  pois é uma escola que abrange muito conhecimento.', 'Positivo'),
	('"Que o instituto possui uma ótima qualificação de professores, além de possuir uma estrutura excelente. Vendo que o ensino Federal tem um peso maior no currículo, pois  o ensino é de boa qualidade e bem rígido preparando o aluno para uma universidade. Além de falar das coisas boas também explico os pontos negativos, que são: a indisponibilidade de transporte nos contra turnos que apesar de ter o auxílio não supre totalmente os gastos do aluno além de ter muitos atrasos, isso ocasiona em desistência ou perdas das aulas e o aluno acabar não passando de série. Ademais tem a questão de muitos professores não entenderem a situação do aluno, sem levar em consideração que o aluno teve um ensino fundamental precário, sem ter acesso a  internet tanto na escola quanto em casa, o que ocasiona em perda de atividades, pois o IFBA faz muito uso das TICs, e dessa forma influência no índice de repetentes e desistentes.', 'Neutro'),
	('Tem um ensino de qualidade, é de confiança e te leva diretamente para o mercado de trabalho ', 'Positivo'),
	('purque o emsino e melhor   da para estudar   bem', 'Positivo'),
	('A qualidade de ensino que o Ifba oferece aos alunos.', 'Positivo'),
	('O ensino é excelente, bons professores e boa estrutura para uma boa base de ensino', 'Positivo'),
	('Para aproveitar a oportunidade de ter um instituto federal na região,onde o ensino é técnico e muito bom.', 'Positivo'),
	('O ensino aqui é excelente com professores capacitados e o IFBA é uma das poucas escolas em Seabra que oferece o ensino técnico, além de uma infraestrutura maravilhosa.', 'Positivo'),
	('Além de obter um ensino de qualidade superior a de qualquer outra escola da cidade, irá adquirir nível técnico no curso em que escolher.', 'Positivo'),
	('é que a qualidade do ensino é melhor que os de varias outra escola e já vai li da  uma formação no curso tecnico', 'Positivo'),
	('O ensino é muito avançado e será bom para sua formação acadêmica', 'Positivo'),
	('com o ifba voçê tem ótimas oportunidades e consegue ter condiçoẽs ,ais favoraveis la na frente', 'Positivo'),
	('Possui uma ótima estrutura, ótimos professores e curso técnico, gratuitamente.', 'Positivo'),
	('convenceria um amigo a vim pois,  a escola tem um ensino de boa qualidade e uma estrutura boa.porém deve ter responsabilidade e dedicação para entrar no instituto.', 'Positivo'),
	('falaria sobre a boa qualidade do ensino, as diversas oportunidades que é oferecida aos estudantes, o excelente espaço de estudos, além da oportunidade de fazer um curso técnico junto com o ensino médio.', 'Positivo'),
	('O ifba é uma rede de ensino boa pois oferece ensino diferenciado da maioria das outra escolas estaduais,alem de oferecer um curso integrado e ser referencia no ensino para outros locais de aprendizagem.Ele traz uma noção de como é uma faculdade ', 'Positivo'),
	(' argumentaria sobre o excelente ensino que o ifba oferece', 'Positivo'),
	('Tem uma ótima estrutura e um ensino muito bom', 'Positivo'),
	('falaria sobre o fato do ensino ser melhor que as outras escolas da região e também pelo fato de ser uma escola técnica ', 'Positivo'),
	('A estudar,pois seria uma boa oportunidade e teria mais gente, companhia para trabalhar em equipe e compartilhar novas ideias', 'Positivo'),
	('Que é uma das melhores instituições de ensino da nossa região pela educação de qualidade que o IFBA oferece aos seus alunos e a ótima estrutura do campus.', 'Positivo'),
	('O argumento seria o ensino que é ofertado pelo IFBA, as oportunidades alcançadas a partir da educação, porém, teria os contras dessa indicação que seria a quantidade excessiva de assuntos para se estudar e a correria diária do IFBA', 'Positivo'),
	('O Ifba tem sim um ensino de qualidade,muitas possibilidades de conhecimento etc,porém o instituto de uma certa forma acaba privando o aluno de outras coisas,por exemplo a um momento de lazer,ou seja,ele trás um pressão psicológica e é realmente é pra quer se dedicar inteiramente aos estudos...Então eu deixaria a pessoa refletir sobre o meu ponto de vista..."', 'Neutro'),
	('ensino de qualidade, e oportunidades, como cursos, e viagens técnicas, tendo também, vários laboratórios para aulas praticas, e estagio para preparação dos alunos.', 'Positivo'),
	('o ensino do ifba é exelente pois tem professores capacitados e estrutura para ensino muito bom.', 'Positivo')
]
